name: markdownlint

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: markdownlint-cli
      uses: articulate/actions-markdownlint@v1
      with:
        config: .markdownlint.yaml
        ignore: assets
    - name: docusaurus-mdx-checker
      if: always()
      run: |
        npx docusaurus-mdx-checker
    - name: link check
      if: always()
      uses: lycheeverse/lychee-action@v1.8.0
      with:
        fail: true
        args: >
          --config lychee.toml
          --offline "./**/*.md"
